#!/bin/bash

# initial setup of the server
export DEFAULT_AWS_HOST=18.195.63.22

if [ ! $AWS_HOST ]; then
  echo AWS_HOST variable not found
  echo Please enter AWS address:
  read AWS_HOST
else
  echo AWS_HOST=$AWS_HOST
fi

DEFAULT_AWS_KEY_PATH=../aws.pem

if [ ! $AWS_KEY_PATH ]; then
  echo AWS_KEY_PATH variable not found
  echo Using default path: $DEFAULT_AWS_KEY_PATH
  export AWS_KEY_PATH=$DEFAULT_AWS_KEY_PATH
fi
echo AWS_KEY_PATH=$AWS_KEY_PATH

./rsync_deploy live go

ssh -i "$AWS_KEY_PATH" ubuntu@$AWS_HOST "source ~/.bashrc; cd soundmates/server_scripts; bash init_setup.sh"
